### ISSUE TITLE
[컴포넌트 제작] 기본 게시물 틀

### ISSUE THREAD

**Issue by 909back** [SuHuenPyo/dangoon_market#60]
1. 기존 HTML을 JSX로 변경
2. 게시물 overflow시, css 설정
3. 기존 css 모듈화

**Comment by 909back** [comment]
따로 제작하지않고 해당 페이지내에서 직접 작성

**Comment by 07Owuor** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://darksouls2.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://darksouls2.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
TimmyKwesi, @zxl6866, @rainb3rry, @Nana12345678910, @amauricarrillo, @npwork, @winsonwq, @ayuLiao, @lanjlon, @ct12, @david7979, @lxrxinyang, @Wenya0422, @TiagoFuelber, @AmberWa, @dejardim, @mxismean, @tokedo, @MitHwo34, @bubay23, @harlock-0xpa, @CryptoYuyyy02, @belgraderichard47, @yecllsl, @transmissions11, @lilyDong, @dustinkrejci5r, @ghaliomar, @nimrc, @gusluna, @camerongamble36, @johntheocs, @Itsme-Munch, @zynth-punk, @konstantinkrumin, @SeshatCZ, @Apoll95, @IndieMinimalist, @wuwuwu111111, @zhukunpenglinyutong, @DavNaty, @duongthanhtung112, @rocketapps1, @GIPPERMORF, @BataBoom, @brust8023, @BestNathan, @aohaichen, @a1072619378, @Timkasimka7882difoi, @ppooyyiu09, @rollingStone91, @NeerajGodiyal, @1Bittium, @hitflame, @rakauchuk, @ruddhisundar, @posrix, @dennis-gonzales, @jamielhf, @wendellmeset, @headson, @gooberville209, @jack201901, @zhangxiangliang, @aoudiamoncef, @goldcoast, @0xmitamo, @wen81643956, @amoralozano, @Loupsteb, @oleggrunin, @ethever, @guilherssousa, @boosixnew, @mhrnik, @HengY1Cola, @lxiiiixi, @dizena, @raoanqi, @setkyar, @ChenRunPing, @neatonk, @JohnIgha, @obiot, @GemsGame, @Dubersnack, @ilocowizhtkovitch, @sanqi2013, @damnern12807, @0x-leen, @LifeSweeteneryasit, @linhpq0610, @vaishnavravi33, @fatihsen-dev, @lyhourchhen, @moorara, @iMyth, @moeid3
